services:
  cadnano2:
    image: subhajitroy/cadnano:latest
    container_name: cadnano2-gui
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # X11 forwarding for GUI support
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY:-~/.Xauthority}:/home/cadnano/.Xauthority:ro
      # Data persistence
      - cadnano_data:/home/cadnano/data
      - cadnano_projects:/home/cadnano/projects
    stdin_open: true
    tty: true
    command: /home/cadnano/start_cadnano.sh

volumes:
  cadnano_data:
    driver: local
  cadnano_projects:
    driver: local